package de.viadee.CarInsurance;





rule "Older than 25 over 340hp has medium risk" 
	 lock-on-active true
	 when
		variable :Ownership( car.hp > "160" , customer.age > "25.500" , car.hp > "340" )

	 then
modify(variable) {risk="medium"};
				end
rule "Older than 65 between 188hp and 340hp has medium risk" 
	 lock-on-active true
	 when
		variable :Ownership( car.hp > "160" , customer.age > "25.500" , car.hp <= "340" , customer.age > "64.500" , car.hp > "187.500" )

	 then
modify(variable) {risk="medium"};
				end
rule "Older than 65 between 160hp and 188hp has low risk" 
	 lock-on-active true
	 when
		variable :Ownership( car.hp > "160" , customer.age > "25.500" , car.hp <= "340" , customer.age > "64.500" , car.hp <= "187.500" )

	 then
modify(variable) {risk="low"};
				end
rule "Older than 25 younger than 65 in an Audi between 160hp and 340hp has low risk" 
	 lock-on-active true
	 when
		variable :Ownership( car.hp > "160" , customer.age > "25.500" , car.hp <= "340" , customer.age <= "64.500" , car.brand == "Audi" )

	 then
modify(variable) {risk="low"};
				end
rule "Between 60 and 65 in Mercedes with between 160hp and 340hp has meidum risk" 
	 lock-on-active true
	 when
		variable :Ownership( car.hp > "160" , customer.age > "25.500" , car.hp <= "340" , customer.age <= "64.500" , car.brand == "Mercedes" , customer.age > "60.500" )

	 then
modify(variable) {risk="medium"};
				end
rule "Between 25 and 60 in Mercedes with between 160hp and 340hp has low risk" 
	 lock-on-active true
	 when
		variable :Ownership( car.hp > "160" , customer.age > "25.500" , car.hp <= "340" , customer.age <= "64.500" , car.brand == "Mercedes" , customer.age <= "60.500" )

	 then
modify(variable) {risk="low"};
				end
rule "Between 25 and 65 in Volkswagen with between 160hp and 340hp has low risk" 
	 lock-on-active true
	 when
		variable :Ownership( car.hp > "160" , customer.age > "25.500" , car.hp <= "340" , customer.age <= "64.500" , car.brand == "Volkswagen" )

	 then
modify(variable) {risk="low"};
				end
rule "Under 25 over 160hp has high risk" 
	 lock-on-active true
	 when
		variable :Ownership( car.hp > "160" , customer.age <= "25.500" )

	 then
modify(variable) {risk="high"};
				end
rule "Over 25 between 60hp and 160hp has low risk" 
	 lock-on-active true
	 when
		variable :Ownership( car.hp <= "160" , car.hp > "60" , customer.age > "25.500" )

	 then
modify(variable) {risk="low"};
				end
rule "Under 25 between 60hp and 160hp has medium risk" 
	 lock-on-active true
	 when
		variable :Ownership( car.hp <= "160" , car.hp > "60" , customer.age <= "25.500" )

	 then
modify(variable) {risk="medium"};
				end
rule "Under 60hp has low risk" 
	 lock-on-active true
	 when
		variable :Ownership( car.hp <= "160" , car.hp <= "60" )

	 then
modify(variable) {risk="low"};
				end

